CREATE TYPE "public"."grn_status" AS ENUM('Draft', 'Posted', 'Reversed');--> statement-breakpoint
CREATE TYPE "public"."invoice_status" AS ENUM('Draft', 'Entered', 'Matched', 'Approved', 'Partially Paid', 'Paid', 'Disputed', 'Cancelled');--> statement-breakpoint
CREATE TYPE "public"."material_request_status" AS ENUM('Requested', 'Approved', 'Issued', 'Rejected');--> statement-breakpoint
CREATE TYPE "public"."payment_status" AS ENUM('Draft', 'Posted', 'Cancelled');--> statement-breakpoint
CREATE TYPE "public"."po_status" AS ENUM('Draft', 'Issued', 'Partially Received', 'Fully Received', 'Closed', 'Cancelled');--> statement-breakpoint
CREATE TYPE "public"."pr_status" AS ENUM('Draft', 'Submitted', 'Approved', 'Rejected', 'PO Created', 'Closed', 'Cancelled');--> statement-breakpoint
CREATE TYPE "public"."priority" AS ENUM('Low', 'Medium', 'High', 'Urgent');--> statement-breakpoint
CREATE TYPE "public"."quotation_status" AS ENUM('Pending', 'Accepted', 'Rejected');--> statement-breakpoint
CREATE TYPE "public"."rfq_status" AS ENUM('Created', 'Sent', 'Closed');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('Admin', 'Procurement', 'Store', 'Dept', 'Finance', 'Vendor');--> statement-breakpoint
CREATE TYPE "public"."stock_movement_type" AS ENUM('Receipt', 'Issue', 'Transfer', 'Adjustment+', 'Adjustment-', 'Reversal');--> statement-breakpoint
CREATE TYPE "public"."stock_reference_type" AS ENUM('GRN', 'Material Request', 'Stock Transfer', 'Stock Count', 'Adjustment', 'GRN Reversal');--> statement-breakpoint
CREATE TABLE "activity_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"user_name" varchar(100),
	"action" text NOT NULL,
	"description" text,
	"entity_type" varchar(50),
	"entity_id" integer,
	"before_data" jsonb,
	"after_data" jsonb,
	"payload" jsonb,
	"timestamp" timestamp DEFAULT now(),
	"module" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" text,
	"uom" varchar(20),
	CONSTRAINT "categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "document_sequences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_sequences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"doc_type" varchar(30) NOT NULL,
	"fiscal_year" integer NOT NULL,
	"prefix" varchar(20) NOT NULL,
	"last_number" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "grn_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grn_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grn_id" integer NOT NULL,
	"po_item_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"received_qty" numeric(12, 2) NOT NULL,
	"accepted_qty" numeric(12, 2) NOT NULL,
	"rejected_qty" numeric(12, 2) NOT NULL,
	"unit_cost" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"rejection_reason" text,
	"disposition" varchar(30) DEFAULT 'Accepted',
	CONSTRAINT "grn_items_received_qty_positive_chk" CHECK ("grn_items"."received_qty" > 0),
	CONSTRAINT "grn_items_accepted_qty_non_negative_chk" CHECK ("grn_items"."accepted_qty" >= 0),
	CONSTRAINT "grn_items_rejected_qty_non_negative_chk" CHECK ("grn_items"."rejected_qty" >= 0),
	CONSTRAINT "grn_items_received_balance_chk" CHECK ("grn_items"."accepted_qty" + "grn_items"."rejected_qty" <= "grn_items"."received_qty")
);
--> statement-breakpoint
CREATE TABLE "grns" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grn_no" varchar(50) NOT NULL,
	"po_id" integer NOT NULL,
	"received_date" timestamp DEFAULT now(),
	"received_by" integer,
	"warehouse_id" integer NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"warnings" jsonb,
	"status" "grn_status" DEFAULT 'Draft' NOT NULL,
	"posted_at" timestamp,
	"posted_by" integer,
	"reversed_at" timestamp,
	"reversed_by" integer,
	"reversal_reason" text,
	"version_no" integer DEFAULT 1 NOT NULL,
	"deleted_at" timestamp,
	"deleted_by" integer,
	CONSTRAINT "grns_grn_no_unique" UNIQUE("grn_no")
);
--> statement-breakpoint
CREATE TABLE "invoice_lines" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invoice_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoice_id" integer NOT NULL,
	"po_item_id" integer NOT NULL,
	"grn_item_id" integer,
	"item_id" integer NOT NULL,
	"quantity" numeric(12, 2) NOT NULL,
	"unit_price" numeric(12, 2) NOT NULL,
	"tax_rate" numeric(5, 2) DEFAULT '0.00' NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"line_amount" numeric(12, 2) NOT NULL,
	CONSTRAINT "invoice_lines_quantity_positive_chk" CHECK ("invoice_lines"."quantity" > 0),
	CONSTRAINT "invoice_lines_unit_price_non_negative_chk" CHECK ("invoice_lines"."unit_price" >= 0),
	CONSTRAINT "invoice_lines_line_amount_non_negative_chk" CHECK ("invoice_lines"."line_amount" >= 0)
);
--> statement-breakpoint
CREATE TABLE "invoices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoice_no" varchar(50) NOT NULL,
	"vendor_invoice_no" varchar(100) NOT NULL,
	"vendor_id" integer NOT NULL,
	"po_id" integer NOT NULL,
	"date" timestamp DEFAULT now(),
	"due_date" timestamp,
	"currency" varchar(10) DEFAULT 'AED' NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"matched_amount" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"paid_amount" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"balance_amount" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"match_warnings" jsonb,
	"status" "invoice_status" DEFAULT 'Draft' NOT NULL,
	"remarks" text,
	"entered_by" integer,
	"approved_at" timestamp,
	"approved_by" integer,
	"version_no" integer DEFAULT 1 NOT NULL,
	"deleted_at" timestamp,
	"deleted_by" integer,
	CONSTRAINT "invoices_invoice_no_unique" UNIQUE("invoice_no"),
	CONSTRAINT "invoices_amount_non_negative_chk" CHECK ("invoices"."amount" >= 0),
	CONSTRAINT "invoices_matched_amount_non_negative_chk" CHECK ("invoices"."matched_amount" >= 0),
	CONSTRAINT "invoices_paid_amount_non_negative_chk" CHECK ("invoices"."paid_amount" >= 0),
	CONSTRAINT "invoices_balance_amount_non_negative_chk" CHECK ("invoices"."balance_amount" >= 0)
);
--> statement-breakpoint
CREATE TABLE "items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(50) NOT NULL,
	"name" text NOT NULL,
	"category_id" integer,
	"uom_id" integer,
	"price" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"active" boolean DEFAULT true,
	"tax_rate" numeric(5, 2) DEFAULT '0.00',
	"reorder_level" numeric(12, 2) DEFAULT '0.00',
	CONSTRAINT "items_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "material_request_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "material_request_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mr_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"quantity" numeric(12, 2) NOT NULL,
	CONSTRAINT "material_request_items_quantity_positive_chk" CHECK ("material_request_items"."quantity" > 0)
);
--> statement-breakpoint
CREATE TABLE "material_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "material_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"request_no" varchar(50) NOT NULL,
	"requestor_id" integer,
	"department" varchar(100),
	"date" timestamp DEFAULT now(),
	"status" "material_request_status" NOT NULL,
	"version_no" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "material_requests_request_no_unique" UNIQUE("request_no")
);
--> statement-breakpoint
CREATE TABLE "payment_allocations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_allocations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"payment_id" integer NOT NULL,
	"invoice_id" integer NOT NULL,
	"allocated_amount" numeric(12, 2) NOT NULL,
	CONSTRAINT "payment_allocations_allocated_amount_positive_chk" CHECK ("payment_allocations"."allocated_amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"payment_no" varchar(50) NOT NULL,
	"vendor_id" integer NOT NULL,
	"payment_date" timestamp DEFAULT now(),
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"method" varchar(50) NOT NULL,
	"status" "payment_status" DEFAULT 'Draft' NOT NULL,
	"reference_no" varchar(100),
	"remarks" text,
	"created_by" integer,
	"posted_at" timestamp,
	"posted_by" integer,
	"cancelled_at" timestamp,
	"cancelled_by" integer,
	"version_no" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "payments_payment_no_unique" UNIQUE("payment_no"),
	CONSTRAINT "payments_amount_positive_chk" CHECK ("payments"."amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "po_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "po_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"po_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"ordered_qty" numeric(12, 2) NOT NULL,
	"unit_price" numeric(12, 2) NOT NULL,
	"tax_rate" numeric(5, 2) DEFAULT '0.00' NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"received_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"accepted_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"invoiced_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"paid_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"cancelled_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"price_variance_pct" numeric(7, 2) DEFAULT '0.00' NOT NULL,
	CONSTRAINT "po_items_ordered_qty_positive_chk" CHECK ("po_items"."ordered_qty" > 0),
	CONSTRAINT "po_items_unit_price_non_negative_chk" CHECK ("po_items"."unit_price" >= 0),
	CONSTRAINT "po_items_received_qty_non_negative_chk" CHECK ("po_items"."received_qty" >= 0),
	CONSTRAINT "po_items_accepted_qty_non_negative_chk" CHECK ("po_items"."accepted_qty" >= 0),
	CONSTRAINT "po_items_invoiced_qty_non_negative_chk" CHECK ("po_items"."invoiced_qty" >= 0),
	CONSTRAINT "po_items_cancelled_qty_non_negative_chk" CHECK ("po_items"."cancelled_qty" >= 0)
);
--> statement-breakpoint
CREATE TABLE "pr_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pr_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pr_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"quantity" numeric(12, 2) NOT NULL,
	"required_date" timestamp,
	CONSTRAINT "pr_items_quantity_positive_chk" CHECK ("pr_items"."quantity" > 0)
);
--> statement-breakpoint
CREATE TABLE "purchase_orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"po_no" varchar(50) NOT NULL,
	"pr_id" integer,
	"rfq_id" integer,
	"vendor_id" integer NOT NULL,
	"date" timestamp DEFAULT now(),
	"currency" varchar(10) DEFAULT 'AED' NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(12, 2) NOT NULL,
	"price_variance_pct" numeric(7, 2) DEFAULT '0.00' NOT NULL,
	"variance_alert" boolean DEFAULT false NOT NULL,
	"status" "po_status" DEFAULT 'Draft' NOT NULL,
	"delivery_date" timestamp,
	"issued_at" timestamp,
	"issued_by" integer,
	"closed_at" timestamp,
	"cancelled_at" timestamp,
	"cancelled_by" integer,
	"version_no" integer DEFAULT 1 NOT NULL,
	"deleted_at" timestamp,
	"deleted_by" integer,
	CONSTRAINT "purchase_orders_po_no_unique" UNIQUE("po_no"),
	CONSTRAINT "purchase_orders_total_non_negative_chk" CHECK ("purchase_orders"."total_amount" >= 0)
);
--> statement-breakpoint
CREATE TABLE "purchase_requisitions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "purchase_requisitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pr_no" varchar(50) NOT NULL,
	"requestor_id" integer,
	"department" varchar(100),
	"date" timestamp DEFAULT now(),
	"priority" "priority" NOT NULL,
	"status" "pr_status" DEFAULT 'Draft' NOT NULL,
	"justification" text,
	"submitted_at" timestamp,
	"approved_at" timestamp,
	"approved_by" integer,
	"rejected_at" timestamp,
	"rejected_by" integer,
	"rejection_reason" text,
	"closed_at" timestamp,
	"cancelled_at" timestamp,
	"cancelled_by" integer,
	"version_no" integer DEFAULT 1 NOT NULL,
	"deleted_at" timestamp,
	"deleted_by" integer,
	CONSTRAINT "purchase_requisitions_pr_no_unique" UNIQUE("pr_no")
);
--> statement-breakpoint
CREATE TABLE "quotation_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quotation_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quotation_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"qty" numeric(12, 2) NOT NULL,
	"unit_price" numeric(12, 2) NOT NULL,
	"tax_rate" numeric(5, 2) DEFAULT '0.00' NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"awarded_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"price_variance_pct" numeric(7, 2) DEFAULT '0.00' NOT NULL,
	CONSTRAINT "quotation_items_qty_positive_chk" CHECK ("quotation_items"."qty" > 0),
	CONSTRAINT "quotation_items_price_non_negative_chk" CHECK ("quotation_items"."unit_price" >= 0)
);
--> statement-breakpoint
CREATE TABLE "quotations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quotations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rfq_id" integer NOT NULL,
	"vendor_id" integer NOT NULL,
	"currency" varchar(10) DEFAULT 'AED' NOT NULL,
	"base_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"tax_amount" numeric(14, 2) DEFAULT '0.00' NOT NULL,
	"total_amount" numeric(12, 2) NOT NULL,
	"delivery_date" timestamp,
	"notes" text,
	"submitted_date" timestamp DEFAULT now(),
	"status" "quotation_status" DEFAULT 'Pending' NOT NULL,
	"version_no" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rfq_vendors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rfq_vendors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rfq_id" integer NOT NULL,
	"vendor_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rfqs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rfqs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rfq_no" varchar(50) NOT NULL,
	"pr_id" integer,
	"created_date" timestamp DEFAULT now(),
	"due_date" timestamp,
	"status" "rfq_status" DEFAULT 'Created' NOT NULL,
	CONSTRAINT "rfqs_rfq_no_unique" UNIQUE("rfq_no")
);
--> statement-breakpoint
CREATE TABLE "stock_levels" (
	"item_id" integer NOT NULL,
	"warehouse_id" integer NOT NULL,
	"quantity" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"reserved_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"avg_cost" numeric(12, 4) DEFAULT '0.0000' NOT NULL,
	"min_stock_level" numeric(12, 2) DEFAULT '0.00',
	"version_no" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "stock_levels_item_id_warehouse_id_pk" PRIMARY KEY("item_id","warehouse_id"),
	CONSTRAINT "stock_levels_quantity_non_negative_chk" CHECK ("stock_levels"."quantity" >= 0),
	CONSTRAINT "stock_levels_min_stock_non_negative_chk" CHECK ("stock_levels"."min_stock_level" >= 0)
);
--> statement-breakpoint
CREATE TABLE "stock_reservations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_reservations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item_id" integer NOT NULL,
	"warehouse_id" integer,
	"source_type" varchar(50) NOT NULL,
	"source_id" integer NOT NULL,
	"source_line_id" integer,
	"quantity" numeric(12, 2) NOT NULL,
	"consumed_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"released_qty" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"status" varchar(30) DEFAULT 'Open' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"released_at" timestamp,
	CONSTRAINT "stock_reservations_quantity_positive_chk" CHECK ("stock_reservations"."quantity" > 0)
);
--> statement-breakpoint
CREATE TABLE "stock_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"item_id" integer NOT NULL,
	"warehouse_id" integer NOT NULL,
	"type" "stock_movement_type" NOT NULL,
	"quantity" numeric(12, 2) NOT NULL,
	"unit_cost" numeric(12, 2) DEFAULT '0.00',
	"date" timestamp DEFAULT now(),
	"reference_type" "stock_reference_type" NOT NULL,
	"reference_id" varchar(100) NOT NULL,
	"line_reference_id" integer,
	"source_warehouse_id" integer,
	"target_warehouse_id" integer,
	"notes" text,
	"performed_by" integer,
	"idempotency_key" varchar(100) NOT NULL,
	"reversal_of_transaction_id" integer,
	CONSTRAINT "stock_transactions_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "stock_transactions_quantity_positive_chk" CHECK ("stock_transactions"."quantity" > 0)
);
--> statement-breakpoint
CREATE TABLE "system_settings" (
	"key" varchar(100) PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "uoms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "uoms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(20) NOT NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT "uoms_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" varchar(255) NOT NULL,
	"password" text NOT NULL,
	"role" "role" NOT NULL,
	"department" varchar(100),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "vendors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(20),
	"rating" integer DEFAULT 0,
	"address" text,
	"tax_id" varchar(50),
	"payment_terms" text,
	"contact_person" varchar(100),
	"active" boolean DEFAULT true,
	CONSTRAINT "vendors_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "warehouses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "warehouses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"code" varchar(50),
	"location" text,
	"manager_id" integer,
	CONSTRAINT "warehouses_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grn_items" ADD CONSTRAINT "grn_items_grn_id_grns_id_fk" FOREIGN KEY ("grn_id") REFERENCES "public"."grns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grn_items" ADD CONSTRAINT "grn_items_po_item_id_po_items_id_fk" FOREIGN KEY ("po_item_id") REFERENCES "public"."po_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grn_items" ADD CONSTRAINT "grn_items_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grns" ADD CONSTRAINT "grns_po_id_purchase_orders_id_fk" FOREIGN KEY ("po_id") REFERENCES "public"."purchase_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grns" ADD CONSTRAINT "grns_received_by_users_id_fk" FOREIGN KEY ("received_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grns" ADD CONSTRAINT "grns_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grns" ADD CONSTRAINT "grns_posted_by_users_id_fk" FOREIGN KEY ("posted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grns" ADD CONSTRAINT "grns_reversed_by_users_id_fk" FOREIGN KEY ("reversed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grns" ADD CONSTRAINT "grns_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_po_item_id_po_items_id_fk" FOREIGN KEY ("po_item_id") REFERENCES "public"."po_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_grn_item_id_grn_items_id_fk" FOREIGN KEY ("grn_item_id") REFERENCES "public"."grn_items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_po_id_purchase_orders_id_fk" FOREIGN KEY ("po_id") REFERENCES "public"."purchase_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_entered_by_users_id_fk" FOREIGN KEY ("entered_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "items" ADD CONSTRAINT "items_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "items" ADD CONSTRAINT "items_uom_id_uoms_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uoms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_request_items" ADD CONSTRAINT "material_request_items_mr_id_material_requests_id_fk" FOREIGN KEY ("mr_id") REFERENCES "public"."material_requests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_request_items" ADD CONSTRAINT "material_request_items_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_requests" ADD CONSTRAINT "material_requests_requestor_id_users_id_fk" FOREIGN KEY ("requestor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_allocations" ADD CONSTRAINT "payment_allocations_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_allocations" ADD CONSTRAINT "payment_allocations_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_posted_by_users_id_fk" FOREIGN KEY ("posted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_cancelled_by_users_id_fk" FOREIGN KEY ("cancelled_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "po_items" ADD CONSTRAINT "po_items_po_id_purchase_orders_id_fk" FOREIGN KEY ("po_id") REFERENCES "public"."purchase_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "po_items" ADD CONSTRAINT "po_items_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pr_items" ADD CONSTRAINT "pr_items_pr_id_purchase_requisitions_id_fk" FOREIGN KEY ("pr_id") REFERENCES "public"."purchase_requisitions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pr_items" ADD CONSTRAINT "pr_items_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_pr_id_purchase_requisitions_id_fk" FOREIGN KEY ("pr_id") REFERENCES "public"."purchase_requisitions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_rfq_id_rfqs_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "public"."rfqs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_issued_by_users_id_fk" FOREIGN KEY ("issued_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_cancelled_by_users_id_fk" FOREIGN KEY ("cancelled_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requisitions" ADD CONSTRAINT "purchase_requisitions_requestor_id_users_id_fk" FOREIGN KEY ("requestor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requisitions" ADD CONSTRAINT "purchase_requisitions_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requisitions" ADD CONSTRAINT "purchase_requisitions_rejected_by_users_id_fk" FOREIGN KEY ("rejected_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requisitions" ADD CONSTRAINT "purchase_requisitions_cancelled_by_users_id_fk" FOREIGN KEY ("cancelled_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_requisitions" ADD CONSTRAINT "purchase_requisitions_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotation_items" ADD CONSTRAINT "quotation_items_quotation_id_quotations_id_fk" FOREIGN KEY ("quotation_id") REFERENCES "public"."quotations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotation_items" ADD CONSTRAINT "quotation_items_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotations" ADD CONSTRAINT "quotations_rfq_id_rfqs_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "public"."rfqs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotations" ADD CONSTRAINT "quotations_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfq_vendors" ADD CONSTRAINT "rfq_vendors_rfq_id_rfqs_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "public"."rfqs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfq_vendors" ADD CONSTRAINT "rfq_vendors_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rfqs" ADD CONSTRAINT "rfqs_pr_id_purchase_requisitions_id_fk" FOREIGN KEY ("pr_id") REFERENCES "public"."purchase_requisitions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_levels" ADD CONSTRAINT "stock_levels_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_levels" ADD CONSTRAINT "stock_levels_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_reservations" ADD CONSTRAINT "stock_reservations_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_reservations" ADD CONSTRAINT "stock_reservations_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transactions" ADD CONSTRAINT "stock_transactions_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transactions" ADD CONSTRAINT "stock_transactions_warehouse_id_warehouses_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transactions" ADD CONSTRAINT "stock_transactions_source_warehouse_id_warehouses_id_fk" FOREIGN KEY ("source_warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transactions" ADD CONSTRAINT "stock_transactions_target_warehouse_id_warehouses_id_fk" FOREIGN KEY ("target_warehouse_id") REFERENCES "public"."warehouses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_transactions" ADD CONSTRAINT "stock_transactions_performed_by_users_id_fk" FOREIGN KEY ("performed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouses" ADD CONSTRAINT "warehouses_manager_id_users_id_fk" FOREIGN KEY ("manager_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "document_sequences_doc_type_year_prefix_idx" ON "document_sequences" USING btree ("doc_type","fiscal_year","prefix");--> statement-breakpoint
CREATE UNIQUE INDEX "purchase_requisitions_pr_no_active_idx" ON "purchase_requisitions" USING btree ("pr_no");